In [45]:
import numpy as np


Creating Numpy Arrays


In [15]:
print(np.array([[1, 3], [5, 6], [6, 9]]))

print(np.arange(0, 100, 5))

print(np.zeros((4, 2), np.int8))

print(np.ones((8, 8)))

#Start and Stop, plus how many numbers inbetween
print(np.linspace(3, 20, 100))

#Identity Matrix
print(np.eye(5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Randomly Generating Data

In [38]:
#Uniform Distribution
print(np.random.rand(5,9))

#Standard Normal Distribution
print(np.random.randn(3,3))

print(np.random.randint(2,55,20))

#Seed
np.random.seed(99)
print(np.random.randint(4, 9, 1))
print(np.random.randint(4, 9, 1))

[[0.4880784  0.82549517 0.03144639 0.80804996 0.56561742 0.2976225
  0.04669572 0.9906274  0.00682573]
 [0.76979303 0.7467671  0.37743894 0.49414745 0.92894839 0.39545404
  0.9739563  0.52441472 0.09361309]
 [0.81330841 0.21168679 0.55434578 0.29226912 0.81614236 0.82804257
  0.22157737 0.6448347  0.09518162]
 [0.41166324 0.09686526 0.144011   0.21219618 0.47665615 0.07761384
  0.23504378 0.006553   0.89864419]
 [0.55223443 0.16754663 0.92887818 0.5420877  0.04175853 0.52487684
  0.64014254 0.80065816 0.83491885]]
[[-1.70429169 -0.24390807 -2.13970379]
 [ 0.86132265  1.7002844  -0.5287848 ]
 [ 1.76347792 -1.12160783 -1.19193417]]
[39 34  5  9 30 47 43  7 47 41 50 16 36 37 54 34 42 29  2 16]
[5]
[7]


NP Array Untilities

In [44]:
#Reshaping
arr = np.arange(0, 33).reshape(11,3)
print(arr)

print(arr.max())
print(arr.min())

print(arr.argmax())
print(arr.argmin())

print(arr.dtype)

print(arr.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]]
32
0
32
0
int64
(11, 3)


Indexing and Selecting

In [54]:
arr = np.arange(0,22)

print(arr[4])
print(arr[3:5])
print(arr[:5])
print(arr[18:])

arr[0:10] = 22
print(arr)

s_arr = arr[0:10]
print(s_arr)
s_arr[:] = 0
print(arr)

s_arr = arr[0:10].copy()
print(s_arr)
s_arr[:] = 99
print(arr)


4
[3 4]
[0 1 2 3 4]
[18 19 20 21]
[22 22 22 22 22 22 22 22 22 22 10 11 12 13 14 15 16 17 18 19 20 21]
[22 22 22 22 22 22 22 22 22 22]
[ 0  0  0  0  0  0  0  0  0  0 10 11 12 13 14 15 16 17 18 19 20 21]
[0 0 0 0 0 0 0 0 0 0]
[ 0  0  0  0  0  0  0  0  0  0 10 11 12 13 14 15 16 17 18 19 20 21]


In [66]:
arr = np.arange(5, 46, 5).reshape(3,3)
print(arr.shape)
print(arr[0])
print(arr[-1])

print(arr[1][1])
print(arr[1,1])

print(arr[:2,1:])

arr = np.arange(1,11)
bool_arr = np.arange(1,11) > 4
print(bool_arr)
print(arr[bool_arr])

print(arr[arr>4])

(3, 3)
[ 5 10 15]
[35 40 45]
25
25
[[10 15]
 [25 30]]
[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


Operators

In [73]:
arr = np.arange(1,11)
print(arr)
print(arr + 5)
print(arr + arr)
print(arr / arr)
print(arr / 0)
print(np.sqrt(arr))

print(np.sin(arr))
print(np.log(arr))

arr = np.random.rand(20)

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.var())
print(arr.std())

arr = np.arange(0,25).reshape(5,5)
print(arr)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[inf inf inf inf inf inf inf inf inf inf]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
9.869552698157337
0.49347763490786684
0.966070536896846
0.09737991316630722
0.31205754784383477
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
300
[50 55 60 65 70]
[ 10  35  60  85 110]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
